image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017
    - GENERATOR: Visual Studio 15 2017 Win64

before_build:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" ..

build_script:
  - cmake --build . --config Release

test_script:
  - ps: ../scripts/test.ps1

artifacts:
  - path: 'build/Release/*.exe'
    name: malco
